### ISSUE TITLE
Cannot connect from iOS

### ISSUE THREAD

**Issue by AymanAljabir** [dani3l0/Status#12]
The status is working fine when checking from browser but when I tried on my iOS app that development by @JGeek00 and he deleted his GitHub cannot reach him anyway it's say cannot connect ![image](https://github.com/dani3l0/Status/assets/83619299/1f27eeca-b1b2-4ecd-9042-a51e12591674)

**Comment by dani3l0** [comment]
I can't fix and even reproduce the bug as I have no iOS device anywhere :<

Anyways, are you connecting over plain HTTP? Plain text traffic is often a problem for mobile apps, especially on newer systems, so the only way might be to use HTTPS with trusted cert

**Comment by AymanAljabir** [comment]
I'm connecting by IP address and port 9090 using http and I'm using my mobile phone browser to check and it's working great but via the app it's failed

**Comment by dani3l0** [comment]
Okay, then I'm 90% sure **app wasn't built with _`allow plaintext traffic`_ flag.** Mobile browser is widely used for completely different purposes, from daily internet surfing to accessing routers/homeservers, just like us. That's why it's working correctly. Especially, if u are using Safari.
Native apps (in order to be available in AppStore) might have requirements to use encrypted connections only. Look at social network apps. I guess they're all forced to use HTTPS.

I dunno how is it working on iOS, but on Android there is such flag:
https://developer.android.com/privacy-and-security/risks/cleartext

And, Google Play Store had quite restrictive policy when it comes to cleartext traffic. Allowing it may result in app being dropped from Play Store. Apple may have similar policies applied.

**Comment by AymanAljabir** [comment]
Ah thank you so much I will try using https ❤️

**Comment by AymanAljabir** [comment]
Is it possible to Get https certificate for bare IP address currently I have no domain

**Comment by AymanAljabir** [comment]
Worked fine on https thank you ❤️

**Comment by dani3l0** [comment]
Great to hear. Happy self-hosting!
